# CMake generated Testfile for 
# Source directory: /workspace/tests
# Build directory: /workspace/build-release/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(spatial_hash "/workspace/build-release/tests/test_spatial_hash")
set_tests_properties(spatial_hash PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;61;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(greens_function "/workspace/build-release/tests/test_greens_function")
set_tests_properties(greens_function PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;62;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(agent "/workspace/build-release/tests/test_agent")
set_tests_properties(agent PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;63;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(iron_fallback "/workspace/build-release/tests/test_iron_fallback")
set_tests_properties(iron_fallback PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;64;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(octree "/workspace/build-release/tests/test_octree")
set_tests_properties(octree PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;65;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(fmm "/workspace/build-release/tests/test_fmm")
set_tests_properties(fmm PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;66;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(conjugation "/workspace/build-release/tests/test_conjugation")
set_tests_properties(conjugation PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;67;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(z_gradient "/workspace/build-release/tests/test_z_gradient")
set_tests_properties(z_gradient PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;68;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(domain_decomp "/workspace/build-release/tests/test_domain_decomp")
set_tests_properties(domain_decomp PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;69;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(acetate_mete "/workspace/build-release/tests/test_acetate_mete")
set_tests_properties(acetate_mete PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;70;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(protease_decay "/workspace/build-release/tests/test_protease_decay")
set_tests_properties(protease_decay PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;71;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(oxygen_gradient "/workspace/build-release/tests/test_oxygen_gradient")
set_tests_properties(oxygen_gradient PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;72;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(O2_growth_boost "/workspace/build-release/tests/test_O2_growth_boost")
set_tests_properties(O2_growth_boost PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;73;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(mucin_liberation "/workspace/build-release/tests/test_mucin_liberation")
set_tests_properties(mucin_liberation PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;74;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(advection_peristaltic "/workspace/build-release/tests/test_advection_peristaltic")
set_tests_properties(advection_peristaltic PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;75;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(ethanolamine "/workspace/build-release/tests/test_ethanolamine")
set_tests_properties(ethanolamine PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;76;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(adaptive_dt "/workspace/build-release/tests/test_adaptive_dt")
set_tests_properties(adaptive_dt PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;77;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(agent_transfer "/workspace/build-release/tests/test_agent_transfer")
set_tests_properties(agent_transfer PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;78;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(fix_registry "/workspace/build-release/tests/test_fix_registry")
set_tests_properties(fix_registry PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;79;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(path_utils "/workspace/build-release/tests/test_path_utils")
set_tests_properties(path_utils PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;80;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(input_parser "/workspace/build-release/tests/test_input_parser")
set_tests_properties(input_parser PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;81;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(config_ingestion "/workspace/build-release/tests/test_config_ingestion")
set_tests_properties(config_ingestion PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;84;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(bacteriocin "/workspace/build-release/tests/test_bacteriocin")
set_tests_properties(bacteriocin PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;87;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(receptor "/workspace/build-release/tests/test_receptor")
set_tests_properties(receptor PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;88;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(mutation "/workspace/build-release/tests/test_mutation")
set_tests_properties(mutation PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;89;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(fur "/workspace/build-release/tests/test_fur")
set_tests_properties(fur PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;90;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(cdi "/workspace/build-release/tests/test_cdi")
set_tests_properties(cdi PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;91;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(motility "/workspace/build-release/tests/test_motility")
set_tests_properties(motility PROPERTIES  LABELS "unit" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;92;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(scaling_benchmark "/workspace/build-release/tests/test_scaling_benchmark")
set_tests_properties(scaling_benchmark PROPERTIES  LABELS "benchmark;slow" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;95;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(mechanics "/workspace/build-release/tests/test_mechanics")
set_tests_properties(mechanics PROPERTIES  LABELS "unit;slow" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;98;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(immunity_escape "/workspace/build-release/tests/test_immunity_escape")
set_tests_properties(immunity_escape PROPERTIES  LABELS "unit;slow" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;99;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(smoke "/workspace/build-release/tests/test_smoke")
set_tests_properties(smoke PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;102;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(config_diversity "/workspace/build-release/tests/test_config_diversity")
set_tests_properties(config_diversity PROPERTIES  LABELS "integration" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;103;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(openmp_parity "/workspace/build-release/tests/test_openmp_parity")
set_tests_properties(openmp_parity PROPERTIES  LABELS "openmp" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;106;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(hdf5_roundtrip "/workspace/build-release/tests/test_hdf5_roundtrip")
set_tests_properties(hdf5_roundtrip PROPERTIES  LABELS "integration;hdf5" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;109;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(hdf5_checkpoint "/workspace/build-release/tests/test_hdf5_checkpoint")
set_tests_properties(hdf5_checkpoint PROPERTIES  LABELS "integration;hdf5" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;110;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(hdf5_roundtrip_parallel "/usr/bin/mpiexec" "-n" "2" "/workspace/build-release/tests/test_hdf5_roundtrip")
set_tests_properties(hdf5_roundtrip_parallel PROPERTIES  LABELS "integration;mpi;hdf5" PASS_REGULAR_EXPRESSION "All HDF5 round-trip tests passed" RESOURCE_LOCK "mpi" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;113;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(mpi_multi_rank "/usr/bin/mpiexec" "-n" "2" "/workspace/build-release/tests/test_mpi_multi_rank")
set_tests_properties(mpi_multi_rank PROPERTIES  LABELS "integration;mpi" PASS_REGULAR_EXPRESSION "All MPI multi-rank tests passed" RESOURCE_LOCK "mpi" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;129;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(greens_function_gpu "/workspace/build-release/tests/test_greens_function_gpu")
set_tests_properties(greens_function_gpu PROPERTIES  LABELS "gpu" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;142;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(gpu_smoke "/workspace/build-release/tests/test_gpu_smoke")
set_tests_properties(gpu_smoke PROPERTIES  LABELS "gpu" _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;54;add_test;/workspace/tests/CMakeLists.txt;143;gutibm_add_test;/workspace/tests/CMakeLists.txt;0;")
